### ISSUE TITLE
Doesn't appear to do anything? External refs are still there? 

### ISSUE THREAD

**Issue by tony-gutierrez** [WindomZ/swagger-merger#24]
I tried using this to process a swagger.json file which had refs to a "submodels.json" file. After it is done, the refs are exactly the same.

**Comment by frodeaa** [comment]
@tony-gutierrez Experiences similar issue when trying to including pats using refs

    paths:
        /hello
            get
            ....
        $ref: "./paths/more.yaml

but this worked for me

    paths:
        /hello
            get
            ....
        $ref#more: "./paths/more.yaml

**Comment by tony-gutierrez** [comment]
swagger-combine from npm combined everything fine. Its not cli but didnt take long to get running.

**Comment by WindomZ** [comment]
Thanks @frodeaa answer 👍 

@tony-gutierrez, do you have a similar problem?

There is a difference here: 
- `$ref` Includes a single-level of swagger file;
- `$ref#*` Includes a multi-level of swagger file.

You can see from the [echo](https://github.com/WindomZ/swagger-merger/tree/master/example/echo) and [petstore_simple](https://github.com/WindomZ/swagger-merger/tree/master/example/petstore_simple) examples.

WHY?
Because a error in
```
"paths": {
    "$ref": "./paths/pets.json",
    "$ref": "./paths/pets-id.json"
}
```
so, it works in
```
"paths": {
    "$ref#pets": "./paths/pets.json",
    "$ref#pets-id": "./paths/pets-id.json"
}
```

Here's another solution [petstore_domain](https://github.com/WindomZ/swagger-merger/tree/master/example/petstore_domain) with `$ref`
